### ISSUE TITLE
相談内容のページの文言を静岡市用に変更する

### ISSUE THREAD

**Issue by kazuomatz** [kazuomatz/covid19#11]
## 改善詳細 / Details of Improvement

 一応、ここを参考に...
https://www.city.shizuoka.lg.jp/388_000101.html#h2_3
下記のよう修正する。

（デザインにあわせて、Faxは表示しない、文章削る等が必要そう。）

【帰国者・接触者相談センター】
電話番号：054-249-2221
（F A X：054-294-3153）
受付時間：24時間対応（土日・祝日も実施）
※こちらへの連絡は、体調に不安のある方のみお願いします。
　 その他の相談につきましては、開庁日に下記の一般的な相談窓口でご対応いたします。

新型コロナウイルス感染症に関する一般的なご相談はこちらまでお願いいたします。
【静岡市保健所　保健予防課】
電話番号：054-249-3172
受付時間：8時30分～17時15分（平日）

**Comment by nakamura8nao** [comment]
こちら着手します。

**Comment by kazuomatz** [comment]
静岡市の確認がとれたのでColseします。
