### ISSUE TITLE
最新のお知らせの表示内容・取得方法

### ISSUE THREAD

**Issue by harumakiyukko** [kazuomatz/covid19#9]
## 改善詳細 / Details of Improvement
- 最新のお知らせの表示内容・取得方法はGoogleスプレッドシートでということになりそう。
　（Backlogを見れる人は：https://covid-sz.backlog.com/view/START_UP-1）

## 今後のTODO

- [x] スプレッドシートが決定したらURLを共有
- [x] script.google.comでスプレッドシートをAPI化
- [x] 表示処理作成

**Comment by kazuomatz** [comment]
Google SpreadSheet APIを使って取得してnews.jsonに変換するプログラムを作って対応します。

**Comment by kazuomatz** [comment]
実装完了しました。
